name: Windows

on:
  push:
    branches-ignore: [ '**wasm**', '**android**', '**linux**', '**bsd**', '**haiku**', '**macos**', '**ios**' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: webbrowser=TRACE

jobs:
  build:
    name: Build
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, '#build-') || contains(github.event.head_commit.message, '#build-windows') }}
    strategy:
      max-parallel: 1
      matrix:
        rust: [stable, beta]
    continue-on-error: ${{ matrix.rust != 'stable' && matrix.rust != 'beta' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Install specific rust version
        run: |
          rustup install ${{ matrix.rust }} --profile minimal
          rustup component add --toolchain ${{ matrix.rust }} rustfmt clippy
      - name: Compile
        run: cargo +${{ matrix.rust }} build
      - name: Run Tests
        run: cargo +${{ matrix.rust }} test --all --locked --verbose
      - name: Run Tests (hardened)
        run: cargo +${{ matrix.rust }} test --features hardened --locked --verbose --test test_windows tests::test_hardened_mode
      - name: Check Code Formatting
        if: ${{ matrix.rust == 'stable' || matrix.rust == 'beta' }}
        run: cargo +${{ matrix.rust }} fmt --all -- --check
      - name: Lints
        if: ${{ matrix.rust == 'stable' || matrix.rust == 'beta' }}
        run: cargo +${{ matrix.rust }} clippy --all-targets -- -D warnings
